#!/bin/bash


#Variables:

CPU_THRESHOLD=1
MEM_THRESHOLD=1
DISK_THERSHOLD=1
#Function to chech CPU usage:
check_cpu_usage() {

	cpu_usage=$(top -bn1 | grep "Cpu(s)" | awk '{print $2 + $4}')
	if (( $(echo "$cpu_usage > $CPU_THRESHOLD" | bc -l) ));
	then
		echo "High CPU Usage: $cpu_usage%"
	fi
}


#Function to check Memory Usage:
check_memory_usage() {
	mem_usage=$(free | grep Mem | awk '{print $3/$2 * 100.0}')
	if (( $(echo "$mem_usage > $MEM_THRESHOLD" | bc -l) ));
	then 
		echo "High Memory Usage: $mem_usage%"
	fi
}

#Function to check Disk Usage:
check_disk_usage() {
	disk_usage=$(df / | tail -1 | awk '{print $5}' | sed 's/%//')
	if [ "$disk_usage" -gt "$DISK_THERSHOLD" ];
	then 
		echo "High Disk Usage: $disk_usage%"
	fi
}

#Running Functions:

check_disk_usage
check_memory_usage
check_cpu_usage

